name: SonarQube Quality Gate Check
description: >
  Check if a project / analysis passed the Quality Gate check
branding:
  icon: check
  color: green
runs:
  using: "composite"
  steps:
    - id: quality-gate-check
      run: $GITHUB_ACTION_PATH/script/check-quality-gate.sh "${{ inputs.scanMetadataReportFile  }}" "${{ inputs.pollingTimeoutSec }}"
      shell: bash
inputs:
  scanMetadataReportFile:
    description: Location of the scanner metadata report file
    required: false
    default: .scannerwork/report-task.txt
  pollingTimeoutSec:
    description: "The maximal time (in seconds) to poll for SonarQube's Quality Gate. Default: 300."
    required: false
    default: "300"
outputs:
  quality-gate-status:
    description: >
      The resulting Quality Gate Status value of PASSED, WARN or FAILED
    value: ${{ steps.quality-gate-check.outputs.quality-gate-status }}
